builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: tgz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - images/**
      - example-config.yml
      - install.sh
      - uninstall.sh
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: true
changelog:
  sort: asc
